language: java

notifications:
  slack: markreinardde-kq42908:uaK0RMwD7UvsQmqyWcUWrIS7

addons:
  sonarcloud:
    organization: "markreinarddennisorg" # the key of the org you chose at step #3
    token:
      secure: "36fecc060db1b2300c97280716373d9bd38cffbf" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

script:
  - mvn site
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=false -Dmaven.test.skip=false -B -V
