language: java

mvn sonar:sonar \
  -Dsonar.projectKey=markdenisreinard \
  -Dsonar.organization=mark-dlc-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=bd9bd6401835cf34c6a39b26b76a4c007b81a601
